src/VDT2/ViewModels/ConsultaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VDT2.ViewModels
{
    public class ConsultaViewModel
    {
        public List<Models.LocalInspecao> ListaLocalInspecao { get; set; }
        public List<Models.LocalCheckPoint> ListaLocalCheckPoint { get; set; }

        public List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> ListaMarca { get; set; }
        public List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> ListaModelo { get; set; }

        public List<Models.AvArea> ListaArea { get; set; }
        public List<Models.AvCondicao> ListaCondicao { get; set; }
        public List<Models.AvDano> ListaDano { get; set; }
        public List<Models.AvQuadrante> ListaQuadrante { get; set; }
        public List<Models.AvGravidade> ListaGravidade { get; set; }
        public List<Models.AvSeveridade> ListaSeveridade { get; set; }
        public Models.Cliente Cliente { get; set; }

        public List<Models.Transportador> ListaTransportador { get; set; }

        public string VIN_6 { get; set; }
        public string VIN { get; set; }

        public List<int> Marca_ID { get; set; }
        public List<int> Modelo_ID { get; set; }
        public List<int> LocalInspecao_ID { get; set; }
        public List<int> LocalCheckPoint_ID { get; set; }
        public List<string> IdTipo { get; set; }
        public List<int> Area_ID { get; set; }
        public List<int> Condicao_ID { get; set; }
        public List<int> Dano_ID { get; set; }
        public List<int> Quadrante_ID { get; set; }
        public List<int> Gravidade_ID { get; set; }
        public List<int> Severidade_ID { get; set; }
        public string Fabrica { get; set; } = "";
        public string Transporte { get; set; } = "";
        public string DanoOrigem { get; set; } = "";
        public string TransportadorMaritimo { get; set; } = ""; 
        public string TransportadorTerrestre { get; set; } = "";
        public string FrotaViagem { get; set; } = "";
        public string NavioNome { get; set; } = "";
        public string Lote { get; set; } = "";

        public DateTime DataInicial {get;set;}
        public DateTime DataFinal { get; set; }
    }
}

src/VDT2/Controllers/ConferenciaController.cs
// <copyright file="ConferenciaController.cs" company="Bureau Veritas">
// Copyright (c) 2017 All Right Reserved
// </copyright>
// <author>Grupo Asserth</author>
// <email>yuri.vasconcelos@grupoasserth.com.br</email>
// <date>2017-03-28</date>
// <summary>Controllers de Conferência</summary>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using VDT2.ViewModels;
using VDT2.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Text;
using VDT2.BLL;
using System.IO;

namespace VDT2.Controllers
{
    public class ConferenciaController : Controller
    {

        private VDT2.Models.Configuracao configuracao { get; set; }
        private string tempErro = "Erro ao processar informação, tente novamente mais tarde";



        /// <summary>
        /// Construtor da classe
        /// <para>Recebe a configuração do aplicativo, usando Dependency Injection</para>
        /// </summary>
        /// <param name="settings">Configuração geral do aplicativo, carregada de appsettings.json</param>
        public ConferenciaController(IOptions<VDT2.Models.Configuracao> settings)
        {
            this.configuracao = settings.Value;
        }

        /// <summary>
        /// Inicio da Conferência. Carrega os dados dos dropdownlists [select options]
        /// </summary>
        /// <returns></returns>
        public IActionResult NovaConferencia()
        {

            if (TempData.Count() > 0)
            {
                ViewData["Mensagem"] = TempData["Mensagem"];
            }

            Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Action acionada: NovaConferencia | Sem Parametros" });


            const string _mensagemLogin = "Usuário não identificado, faça login novamente";

            ConferenciaIndexViewModel conferenciaVM = new ConferenciaIndexViewModel();

            var dadosUsuario = BLL.Login.ExtraiDadosUsuario(this.HttpContext.User.Claims);

            if (dadosUsuario != null)
            {
                var identificacao = this.Request.Cookies["Usr"];
                if (identificacao != null)
                {
                    var objUsuario = JsonConvert.DeserializeObject<Models.Usuario>(identificacao);
                    dadosUsuario.Usuario = objUsuario;

                    conferenciaVM.ListaCliente = BLL.Inspecao.ListarClientes(dadosUsuario.UsuarioId, configuracao);

                    conferenciaVM.ListaLocalInspecao = BLL.Inspecao.ListarLocaisInspecao(dadosUsuario.UsuarioId, configuracao, dadosUsuario.Usuario.Locais);

                    conferenciaVM.ListaLocalCheckPoint = BLL.Inspecao.ListarLocalCheckPoint(dadosUsuario.UsuarioId, configuracao);

                    #region EM_ERRO
                    if (conferenciaVM.ListaCliente.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] += conferenciaVM.ListaCliente.FirstOrDefault().MensagemErro;
                    }

                    if (conferenciaVM.ListaLocalInspecao.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] += conferenciaVM.ListaLocalInspecao.FirstOrDefault().MensagemErro;
                    }

                    if (conferenciaVM.ListaLocalCheckPoint.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] += conferenciaVM.ListaLocalCheckPoint.FirstOrDefault().MensagemErro;
                    }
                    #endregion
                }
                else
                {
                    ViewData["MensagemErro"] = _mensagemLogin;
                    return RedirectToAction("Index", "Home");
                }
            }


            else
            {
                ViewData["MensagemErro"] = _mensagemLogin;
                return RedirectToAction("Index", "Home");
            }

            return View("NovaConferencia", conferenciaVM);
        }



        /// <summary>
        /// Listagem de veículos e suas respectivas avarias 2a tela.
        /// </summary>
        /// <param name="conferenciaVM">Dados da conferência</param>
        /// <returns></returns>
        public IActionResult ConferenciaListarVeiculos(ConferenciaIndexViewModel conferenciaVM)
        {

            Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Action acionada: ConferenciaListarVeiculos" });

            const string _mensagemLogin = "Erro ao identificar usuário, tente novamente mais tarde ou faça um novo login";
            const string _mensagemErro = "Não foi possível listar, por favor tente novamente mais tarde ou entre em contato com o suporte técnico";
            ListarConferenciaAvariaViewModel listarConferenciaAvariaVM = new ListarConferenciaAvariaViewModel();
            listarConferenciaAvariaVM.InspAvaria_Conf = new Models.InspAvaria_Conf();

            try
            {

                var dadosUsuario = BLL.Login.ExtraiDadosUsuario(this.HttpContext.User.Claims);
                if (dadosUsuario == null)
                {
                    ViewData["MensagemErro"] = _mensagemLogin;
                    return RedirectToAction("Index", "Home");
                }

                var identificacao = this.Request.Cookies["Usr"];

                if (identificacao == null)
                {
                    ViewData["MensagemErro"] = _mensagemLogin;
                    return RedirectToAction("Index", "Home");
                }

                var objUsuario = JsonConvert.DeserializeObject<Models.Usuario>(identificacao);
                listarConferenciaAvariaVM.Usuario = objUsuario;
                dadosUsuario.Usuario = objUsuario;

                ViewData["UsuarioNome"] = dadosUsuario.Nome;
                ViewData["UsuarioIdentificacao"] = dadosUsuario.Identificacao;


                if (conferenciaVM != null)
                {
                    if (!(conferenciaVM.Cliente_ID == 0 || conferenciaVM.LocalInspecao_ID == 0 || conferenciaVM.LocalCheckPoint_ID == 0 || conferenciaVM.Data == null))
                    {
                        listarConferenciaAvariaVM = RecebeDadosConferenciaTelaConferencia(listarConferenciaAvariaVM, conferenciaVM.Cliente_ID, conferenciaVM.LocalInspecao_ID, conferenciaVM.LocalCheckPoint_ID, conferenciaVM.Data, configuracao);

                        //Realiza a concatenação de inspeções para mandar p/ View
                        StringBuilder sbInspecao = new StringBuilder();
                        if (listarConferenciaAvariaVM.ListaInspAvaria_Conf.Count() > 0)
                        {
                            HashSet<int> controle = new HashSet<int>();

                            foreach (var item in listarConferenciaAvariaVM.ListaInspAvaria_Conf)
                            {
                                //Lógica utilizada para não receber valores duplicados
                                if (!controle.Contains(item.Inspecao_ID))
                                {
                                    sbInspecao.Append($"{item.Inspecao_ID};");
                                    controle.Add(item.Inspecao_ID);
                                }
                            }
                        }

                        listarConferenciaAvariaVM.ConcatInspecoes = sbInspecao.ToString();

                        if (listarConferenciaAvariaVM.ListaInspAvaria_Conf == null)
                        {
                            ViewData["MensagemErro"] = _mensagemErro;
                        }

                        //Preenche dados do cabecalho da proxima view
                        listarConferenciaAvariaVM.InspAvaria_Conf.Data = conferenciaVM.Data;
                        listarConferenciaAvariaVM.InspAvaria_Conf.LocalNome = BLL.Inspecao.ListarLocaisInspecao(dadosUsuario.UsuarioId, configuracao, listarConferenciaAvariaVM.Usuario.Locais).Where(p => p.LocalInspecao_ID == conferenciaVM.LocalInspecao_ID).FirstOrDefault().Nome;

                        var dadosCheckPoint = BLL.Inspecao.ListarLocalCheckPoint(dadosUsuario.UsuarioId, configuracao).Where(p => p.LocalCheckPoint_ID == conferenciaVM.LocalCheckPoint_ID).FirstOrDefault();

                        listarConferenciaAvariaVM.InspAvaria_Conf.CheckPointNome = dadosCheckPoint.Nome_Pt;
                        listarConferenciaAvariaVM.InspAvaria_Conf.Operacao = dadosCheckPoint.Operacao;
                        listarConferenciaAvariaVM.InspAvaria_Conf.TransportadorTipo = dadosCheckPoint.Tipo;
                    }
                    else
                    {
                        ViewData["MensagemErro"] = _mensagemErro;
                    }
                }
                else
                {
                    ViewData["MensagemErro"] = _mensagemErro;
                }

                //Caso tudo ok, retorna a view;
                return View("ListarConferenciaAvarias", listarConferenciaAvariaVM);
            }

            catch (Exception ex)
            {
                Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Excecao = ex, Mensagem = "Erro ao solicitar operacao, ConferenciaListarVeiculos" });

                TempData["Erro"] = tempErro;

                return RedirectToAction("NovaConferencia");
            }

        }

        /// <summary>
        /// Realiza edição das avarias
        /// </summary>
        /// <param name="inspAvaria_ID">ID da avaria</param>
        /// <returns></returns>
        public IActionResult EditarAvarias(int inspAvaria_ID, int inspVeiculo_ID)
        {
            Diag.Log.Grava(new Diag.LogItem() { Nivel = Diag.Nivel.Informacao, Mensagem = $"Action acoinada: EditarAvarias | Parametros: InspAvaria_ID: {inspAvaria_ID}" });

            try
            {
                ConferenciaEditarAvariasViewModel conferenciaEditarAvariasVM = new ConferenciaEditarAvariasViewModel();

src/VDT2/Views/Conferencia/EnviarLista.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model VDT2.ViewModels.ConferenciaListaViewModel

@{
    Layout = "~/Views/Shared/_LayoutConferencia.cshtml";
}

@section Scripts{
    <script src="testesRenderSection.js"></script>
}

<script src="~/js/Conferencia/ConferenciaLista.js" asp-append-version="true"></script>
<form id="frmEnviarLista" asp-controller="Conferencia" asp-action="SalvarLista" method="post" enctype="multipart/form-data">

    <div class="container">
        @if (ViewData["MensagemErro"] != null)
            {
            <div class="alert alert-danger">
                <p>@ViewData["MensagemErro"]</p>
            </div>
        }
    </div>
    <div class="container">
        @if (ViewData["MensagemSucesso"] != null)
            {
            <div class="alert alert-success">
                <p>@ViewData["MensagemSucesso"]</p>
            </div>
        }
    </div>

    <div class="container">
        <h2><strong>Envio de Listas<br /><br /></strong></h2>

        @*Cliente*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaCliente" id="ListaClienteLabelID">Cliente</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaCliente" name="Cliente_ID" class="form-control"
                        asp-items="@(new SelectList(Model.ListaCliente,"Cliente_ID","Nome"))">
                    <option disabled selected>Selecione Cliente</option>
                </select>
            </div>
        </div>

        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label>Data</label>
            </div>

            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input class="form-control" type="date" name="DataLista" />
            </div>
        </div>


        @*Local Inspeção*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaLocalInspecao">Local Inspecao</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaLocalInspecao" name="LocalInspecao_ID" class="form-control" onchange="PreencheListaCheckPoint()"
                        asp-items="@(new SelectList(Model.ListaLocalInspecao,"LocalInspecao_ID","Nome"))">
                    <option disabled selected>Selecione Local</option>
                </select>
            </div>
        </div>


        @*Local CheckPoint*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaLocalCheckPoint">Local CheckPoint</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaLocalCheckPoint" name="LocalCheckPoint_ID" class="form-control"
                        asp-items="@(new SelectList(Model.ListaLocalCheckPoint,"LocalCheckPoint_ID", "Nome_Pt"))">
                    <option disabled selected>Selecione CheckPoint</option>
                </select>
            </div>
        </div>

        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label>Tipo de Lista</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input type="radio" id="radioLoading" name="TipoLista" value="L" checked /> <label for="radioLoading"> Loading</label> <br />
                <input type="radio" id="radioPacking" name="TipoLista" value="P" /> <label for="radioPacking"> Packing</label> <br />
                <input type="radio" id="radioDischarging" name="TipoLista" value="D" /> <label for="radioDischarging"> Discharging</label> <br />
            </div>
        </div>




        @*Lote*@
        <div id="divLote" class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label>Lote</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input type="text" class="form-control" name="lote" id="inputLote" value="" required />
            </div>
        </div>


        @*ARQUIVO*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="Arquivo">Arquivo</label><br /><br /><br />
            </div>

            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input type="file" name="files" id='inputFilesEnviarLista' accept=".txt" class="inputTelaPacking-e-LoadingList" />
            </div>
        </div>


        <div class="row form-group">
            <div class="col col-lg-offset-0 col-md-12 col-sm-12 col-xs-12">
                <button type="button" class="btn btnTelaEnviarLista btn btn-success" id="btnUpload" data-toggle="modal" data-target="#enviarListaModal"><span class="glyphicon glyphicon-ok"> </span> Enviar</button>
                <button type="button" class="btn btnTelaEnviarLista btn btn-danger" onclick="location.href='../Home/Index'"><span class="glyphicon glyphicon-remove"> </span> Cancelar</button>
            </div>
        </div>
    </div>

</form>

<!-- Modal -->
<div id="enviarListaModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Deseja realmente enviar a lista?</h4>
            </div>
            <div class="modal-body">
                <p id="lblConfirmacaoLote"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal" onclick="Enviar()"> Enviar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal"> Voltar</button>
            </div>
        </div>

    </div>
</div>

src/VDT2/Views/Conferencia/LoadingListInicio.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model VDT2.ViewModels.ConferenciaLoadingListViewModel

@{
    Layout = "~/Views/Shared/_LayoutConferencia.cshtml";
}

<script src="~/js/Conferencia/ConferenciaLoadingList.js" asp-append-version="true"></script>

<br />
<form asp-controller="Conferencia" asp-action="LoadingListSalvar" method="post" enctype="multipart/form-data">
    
    <div class="container">
        @if (ViewData["MensagemErro"] != null)
        {
            <div class="alert alert-danger">
                <p>@ViewData["MensagemErro"]</p>
            </div>
        }
    </div>
    <div class="container">
        @if (ViewData["MensagemSucesso"] != null)
        {
            <div class="alert alert-success">
                <p>@ViewData["MensagemSucesso"]</p>
            </div>
        }
    </div>

    <div class="container">

        <h3>Loading List</h3><br/>
        @*Cliente*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaCliente" id="ListaClienteLabelID">Cliente</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaCliente" name="Cliente_ID" class="form-control"
                        asp-items="@(new SelectList(Model.ListaCliente,"Cliente_ID","Nome"))">
                    <option disabled selected>Selecione Cliente</option>
                </select>
            </div>
        </div>

        @*Local Inspeção*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaLocalInspecao">Local Inspecao</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaLocalInspecao" name="LocalInspecao_ID" class="form-control" onchange="PreencheListaCheckPoint()"
                        asp-items="@(new SelectList(Model.ListaLocalInspecao,"LocalInspecao_ID","Nome"))">
                    <option disabled selected>Selecione Local</option>
                </select>
            </div>
        </div>

        @*Local CheckPoint*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="ListaLocalCheckPoint">Local CheckPoint</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <select id="ListaLocalCheckPoint" name="LocalCheckPoint_ID" class="form-control"
                        asp-items="@(new SelectList(Model.ListaLocalCheckPoint,"LocalCheckPoint_ID", "Nome_Pt"))">
                    <option disabled selected>Selecione CheckPoint</option>
                </select>
            </div>
        </div>

        @*Lote*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label>Lote</label>
            </div>
            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input type="text" name="lote" class="form-control" value="" required/>
            </div>
        </div>

        @*ARQUIVO*@
        <div class="row form-group">
            <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                <label for="Arquivo">Arquivo</label>
            </div>

            <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                <input type="file" name="files" accept=".txt" class="inputTelaPacking-e-LoadingList" />
            </div>
        </div><br /><br />

        <div class="row form-group">
            <div class="col col-lg-offset-2 col-lg-12 col-md-12 col-xs-12 col-sm-12">
                <button type="submit" class="btnTelaLoadingListInicio btn btn btn-success">Upload</button>
                <input type="button" class="btnTelaLoadingListInicio btn btn-primary" value="Voltar" onclick="location.href='../Home/Index'">
            </div>
        </div>
    </div>

</form>

src/VDT2/Views/Conferencia/NovaConferencia.cshtml
@*CONFERENCIA*@

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model VDT2.ViewModels.ConferenciaIndexViewModel

@{
    Layout = "~/Views/Shared/_LayoutConferencia.cshtml";
}

<link href="~/css/NovaConferencia.css" rel="stylesheet" />
<script src="~/js/Conferencia/ConferenciaTelaInicial.js" asp-append-version="true"></script>
<div class="container">
    <div class="container" id="EM_ERRO">
        @if (ViewData["Mensagem"] != null)
            {
            <div class="alertaTelaNovaConferencia alert alert-success">
                <p>@ViewData["Mensagem"]</p>
            </div>
        }

        @if (TempData["MensagemErro"] != null)
        {
            <div class="alertaTelaNovaConferencia alert alert-danger">
                <p>@TempData["MensagemErro"]</p>
            </div>

        }
    </div>

    <div class="row">
        <div class="col-col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h3><strong>Conferência de Inspeção</strong></h3><br />
        </div>

        <form asp-controller="Conferencia" asp-action="ConferenciaListarVeiculos" method="post" onSubmit="return ValidarFormularioIndex()">
            <div class="col col-lg-12 col-md-12">
                <br />

                @*Cliente*@
                <div class="row form-group">
                    <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                        <label for="ListaCliente" id="ListaClienteLabelID">Cliente</label>
                    </div>
                    <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                        <select id="ListaCliente" name="Cliente_ID" class="form-control"
                                asp-items="@(new SelectList(Model.ListaCliente,"Cliente_ID","Nome"))">
                            <option disabled selected>Selecione Cliente</option>
                        </select>
                    </div>
                </div>


                @*Local Inspeção*@
                <div class="row form-group">
                    <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                        <label for="ListaLocalInspecao">Local Inspeção</label>
                    </div>
                    <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                        <select id="ListaLocalInspecao" name="LocalInspecao_ID" class="form-control" onchange="PreencheListaCheckPoint()"
                                asp-items="@(new SelectList(Model.ListaLocalInspecao,"LocalInspecao_ID","Nome"))">
                            <option disabled selected>Selecione Local</option>
                        </select>
                    </div>
                </div>

                @*Local CheckPoint*@
                <div class="row form-group">
                    <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                        <label for="ListaLocalCheckPoint">Local CheckPoint</label>
                    </div>
                    <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                        <select id="ListaLocalCheckPoint" name="LocalCheckPoint_ID" class="form-control"
                                asp-items="@(new SelectList(Model.ListaLocalCheckPoint,"LocalCheckPoint_ID", "Nome_Pt"))">
                            <option disabled selected>Selecione CheckPoint</option>
                        </select>
                    </div>
                </div>

                @*Data*@
                <div class="row form-group">
                    <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                        <label>Data</label>
                    </div>
                    <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                        <input type="date" id="data" name="Data" class="form-control" />
                    </div>
                </div>
                <br />

                @*Botões*@
                <br /><br />
                <div class="row">
                    <div class="btnNovaConferencia col col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <button type="submit" class="btnTelaNovaConferencia btn btn-success"><span class="glyphicon glyphicon-search"> </span> Consultar </button>
                        <button type="button" class="btnTelaNovaConferencia btn btn-primary" value="Voltar" onClick="Voltar()"><span class="glyphicon glyphicon-menu-left"></span> Voltar </button>
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>


<script>
    function Voltar() {
        $("#frmVoltar").submit();
    }
</script>

<form id="frmVoltar" asp-action="Index" asp-controller="Home"></form>

src/VDT2/Views/Conferencia/NovaConsulta.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model List<VDT2.Models.Cliente>

@{
    Layout = "~/Views/Shared/_LayoutConferencia.cshtml";
}
<br />


<script src="~/js/Conferencia/ConferenciaNovaConsulta.js" asp-append-version="true"></script>


<div class="container">
    <div class="row form-group">
        <h1>Escolha um cliente para continuar..</h1><br />
        @foreach (var item in Model)
        {
            <ul>
                <li><a id="@item.Cliente_ID" onclick="EnviarForm(@item.Cliente_ID)">@item.Nome</a></li>
            </ul>
        }
    </div>

    <div hidden>
        <form id="formPrincipal" asp-action="ConsultaCliente" asp-controller="Conferencia" method="post">
            <input type="text" name="Cliente_ID" id="inputCliente" />
        </form>
    </div>
</div>

src/VDT2/Views/Conferencia/VisualizarFotosConsulta.cshtml
@model List<VDT2.Models.ImagemAvaria>


@foreach (var item in Model)
{
    <p>@item.Path</p>
    <p>@item.Imagem</p>
}