src/VDT2/Models/Inspecao.cs
// <copyright file="Inspecao.cs" company="Bureau Veritas">
// Copyright (c) 2017 All Right Reserved
// </copyright>
// <author>Grupo Asserth</author>
// <email>yuri.vasconcelos@grupoasserth.com.br</email>
// <date>2017-03-28</date>
// <summary>Models de Inspecao</summary>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace VDT2.Models
{
    public class Inspecao
    {
        [Key]
        public int Inspecao_ID { get; set; }

        public int Cliente_ID { get; set; }

        public int LocalInspecao_ID { get; set; }

        public int LocalCheckPoint_ID { get; set; }

        public int Transportador_ID { get; set; }

        public int FrotaViagem_ID { get; set; }

        public int? Navio_ID { get; set; }

        public int Usuario_ID { get; set; }

        public DateTime Data { get; set; }

        [NotMapped]
        public bool Erro { get; set; }

        [NotMapped]
        public string MensagemErro { get; set; }


        public Inspecao()
        {
            MensagemErro = "";
        }
    }
}

src/VDT2/Controllers/InspecaoController.cs
// <copyright file="InspecaoController.cs" company="Bureau Veritas">
// Copyright (c) 2017 All Right Reserved
// </copyright>
// <author>Grupo Asserth</author>
// <email>yuri.vasconcelos@grupoasserth.com.br</email>
// <date>2017-03-28</date>
// <summary>Controllers de Inspecao</summary>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VDT2.DAL;
using VDT2.ViewModels;
using Microsoft.AspNetCore.Http;
using VDT2.Models;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Mvc.Rendering;
using VDT2.BLL;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Newtonsoft.Json;
using System.Text;

namespace VDT2.Controllers
{
    public class InspecaoController : Controller
    {
        private VDT2.Models.Configuracao Configuracao { get; set; }

        /// <summary>
        /// Construtor da classe
        /// <para>Recebe a configuração do aplicativo, usando Dependency Injection</para>
        /// </summary>
        /// <param name="settings">Configuração geral do aplicativo, carregada de appsettings.json</param>
        public InspecaoController(IOptions<VDT2.Models.Configuracao> settings, IHostingEnvironment environment)
        {
            this.Configuracao = settings.Value;
        }

        /// <summary>
        /// Index()
        /// <para>Inicialização da inspeção - Nova Inspeção</para>
        /// </summary>
        /// <returns></returns>
        public IActionResult NovaInspecao()
        {

            Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Action acionada: NovaInspecao" });

            string _mensagemLogin = "Erro ao validar usuário, por favor realize o login novamente";

            InspecaoDadosGeraisViewModel inspecaoDadosGeraisVM = new InspecaoDadosGeraisViewModel();

            ViewModels.LoginViewModel dadosUsuario = null;

            dadosUsuario = BLL.Login.ExtraiDadosUsuario(this.HttpContext.User.Claims);
            if (dadosUsuario != null)
            {
                ViewData["UsuarioNome"] = dadosUsuario.Nome;
                ViewData["UsuarioIdentificacao"] = dadosUsuario.Identificacao;

                var identificacao = this.Request.Cookies["Usr"];

                if (identificacao != null)
                {
                    var objUsuario = JsonConvert.DeserializeObject<Models.Usuario>(identificacao);
                    dadosUsuario.Usuario = objUsuario;

                    inspecaoDadosGeraisVM.Data = System.DateTime.Today;

                    inspecaoDadosGeraisVM.ListaCliente = BLL.Inspecao.ListarClientes(dadosUsuario.UsuarioId, Configuracao);

                    inspecaoDadosGeraisVM.ListaLocalInspecao = BLL.Inspecao.ListarLocaisInspecao(dadosUsuario.UsuarioId, Configuracao, dadosUsuario.Usuario.Locais);

                    inspecaoDadosGeraisVM.ListaLocalCheckPoint = BLL.Inspecao.ListarLocalCheckPoint(dadosUsuario.UsuarioId, Configuracao);

                    inspecaoDadosGeraisVM.ListaTransportador = BLL.Inspecao.ListarTransportadores(dadosUsuario.UsuarioId, Configuracao);

                    #region EM_ERRO
                    if (inspecaoDadosGeraisVM.ListaLocalInspecao.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] = inspecaoDadosGeraisVM.ListaLocalInspecao.FirstOrDefault().MensagemErro;
                    }
                    if (inspecaoDadosGeraisVM.ListaCliente.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] = inspecaoDadosGeraisVM.ListaCliente.FirstOrDefault().MensagemErro;
                    }
                    if (inspecaoDadosGeraisVM.ListaLocalCheckPoint.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] = inspecaoDadosGeraisVM.ListaLocalCheckPoint.FirstOrDefault().MensagemErro;
                    }
                    if (inspecaoDadosGeraisVM.ListaTransportador.FirstOrDefault().Erro == true)
                    {
                        ViewData["MensagemErro"] = inspecaoDadosGeraisVM.ListaTransportador.FirstOrDefault().MensagemErro;
                    }
                    #endregion

                    return View("NovaInspecao", inspecaoDadosGeraisVM);
                }

                else
                {
                    ViewData["MensagemErro"] = _mensagemLogin;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewData["MensagemErro"] = _mensagemLogin;
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Insere ou atualiza dados de uma nova inspeção ou atualiza inspeção que já está no banco;
        /// </summary>
        /// <param name="inspecaoDadosGeraisVM">Dados do formulário de cadastro de inspeção</param>
        /// <param name="botaoEnviar">Botao acionado pelo usuário - View - NovaInspecao </param>
        /// <returns>Retorna a View (Veiculo)</returns>
        [HttpPost]
        public IActionResult InserirDadosCabecalhoInspecao(InspecaoDadosGeraisViewModel inspecaoDadosGeraisVM, string botaoEnviar)
        {
            Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Action acionada: InserirDadosCabecalhoInspecao | Parametros: Cliente_ID: {inspecaoDadosGeraisVM.Cliente_ID}, Local Inspeção: {inspecaoDadosGeraisVM.LocalInspecao_ID}, LocalCheckPoint: {inspecaoDadosGeraisVM.LocalCheckPoint_ID}, Transportador[Id_Tipo] {inspecaoDadosGeraisVM.IdTipo}, NomeNavio: {inspecaoDadosGeraisVM.NomeNavio}, FrotaViagemNome {inspecaoDadosGeraisVM.FrotaViagemNome}, Em Edição: {inspecaoDadosGeraisVM.Edicao}", });

            string _mensagemLogin = "Erro ao validar usuário, por favor realize o login novamente";

            InspecaoVeiculoViewModel InspecaoVeiculoVM = new InspecaoVeiculoViewModel();
            InspecaoVeiculoVM.InspVeiculo = new Models.InspVeiculo();

            //Verifica dados do usuário
            ViewModels.LoginViewModel dadosUsuario = BLL.Login.ExtraiDadosUsuario(this.HttpContext.User.Claims);

            if (dadosUsuario == null)
            {
                ViewData["MensagemErro"] = _mensagemLogin;

                Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Dados do usuário estão nulos, InserirDadosCabecalhoInspecao" });

                return RedirectToAction("Index", "Home");
            }

            var identificacao = this.Request.Cookies["Usr"];

            if (identificacao == null)
            {
                ViewData["MensagemErro"] = _mensagemLogin;

                Diag.Log.Grava(new Diag.LogItem { Nivel = Diag.Nivel.Informacao, Mensagem = $"Identificacao está nulo, InserirDadosCabecalhoInspecao" });

                return RedirectToAction("Index", "Home");
            }

            var objUsuario = JsonConvert.DeserializeObject<Models.Usuario>(identificacao);

            //Aqui insere Navio, FrotaViagem no banco de dados, além de receber os dados do transportador
            InspecaoVeiculoVM.Inspecao = BLL.Inspecao.MontaDadosInspecao(inspecaoDadosGeraisVM, Configuracao);

            //Atualiza dados
            if (inspecaoDadosGeraisVM.Edicao == 1)
            {
                InspecaoVeiculoVM.Inspecao.Inspecao_ID = inspecaoDadosGeraisVM.Inspecao_ID;

                if (InspecaoVeiculoVM.Inspecao != null)
                {
                    if (InspecaoVeiculoVM.Inspecao.Inspecao_ID != 0)
                    {
                        InspecaoVeiculoVM.Inspecao.Data = InspecaoVeiculoVM.Inspecao.Data;
                        InspecaoVeiculoVM.Inspecao = BLL.Inspecao.Update(InspecaoVeiculoVM.Inspecao, Configuracao);

                        if (InspecaoVeiculoVM.Inspecao.Erro == true)
                        {
                            ViewData["MensagemErro"] = InspecaoVeiculoVM.Inspecao.MensagemErro;
                        }
                        else
                        {
                            ViewData["MensagemSucesso"] = "Inspecao Atualizada com sucesso";
                        }
                    }
                }
            }

            //Insere
            else if (inspecaoDadosGeraisVM.Edicao == 0)
            {
                //Verifica se é um reload do formulário anterior
                string formsubmit = inspecaoDadosGeraisVM.Cliente_ID + inspecaoDadosGeraisVM.LocalInspecao_ID + inspecaoDadosGeraisVM.LocalCheckPoint_ID + inspecaoDadosGeraisVM.FrotaViagemNome + inspecaoDadosGeraisVM.IdTipo;

                var ultimosubmit = this.HttpContext.Session.GetString("formsubmit");

                if (formsubmit != ultimosubmit)
                {
                    this.HttpContext.Session.SetString("formsubmit", formsubmit);
                }
                else
                {
                    Diag.Log.Grava(new Diag.LogItem() { Nivel = Diag.Nivel.Informacao, Mensagem = $"Não foi possível finalizar solicitação. Dados são identicos aos enviados anteriormente - Prevent (f5)" });
                    TempData["MensagemErro"] = "Não é possível atualizar dados identicos aos informados anteriormente!";
                    return RedirectToAction("NovaInspecao");
                }


                InspecaoVeiculoVM.Inspecao = BLL.Inspecao.Inserir(InspecaoVeiculoVM.Inspecao, Configuracao);
                if (InspecaoVeiculoVM.Inspecao != null)
                {
                    if (InspecaoVeiculoVM.Inspecao.Erro == true)
                    {
                        #region EM_ERRO
                        TempData["MensagemErro"] = InspecaoVeiculoVM.Inspecao.MensagemErro;
                        inspecaoDadosGeraisVM.ListaCliente = BLL.Inspecao.ListarClientes(dadosUsuario.UsuarioId, Configuracao);

src/VDT2/Views/Inspecao/Avarias.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model VDT2.ViewModels.VisualizarAvariasViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/Inspecao/VisualizarAvarias.js"></script>

@if (Model == null || Model.Avarias == null)
{
    <div class="alert alert-danger">
        <p><strong>Erro ao inicializar, por favor tente novamente mais tarde ou entre em contato com o suporte técnico</strong></p>
        <br />
        <button class="btn btn-primary" onclick="history.go(-1)">Voltar</button>
    </div>
}
else
{
    <div class="container-fluid">
        <div class="container">
            <div class="row" id="">
                <h4>Chassi: @Model.VIN_6</h4>
                <p><strong>Avarias neste CheckPoint</strong></p>
                <table class="table table-striped table-bordered table-hover">
                    <tr class="danger">
                        <th>Editar</th>
                        <th>Área</th>
                        <th>Condicao</th>
                        <th>Dano</th>
                        <th>Gravidade</th>
                        <th>Quadrante</th>
                        <th>Severidade</th>
                    </tr>
                    @foreach (var item in Model.Avarias)
                {
                        @if (item.InspVeiculo_ID.Equals(Model.InspVeiculo_ID))
                    {
                            <tr>
                                <td><button type="button" value="@item.InspAvaria_ID" onclick="Btn_Click_EditarAvaria(this.value)">Editar</button></td>
                                <td>@item.Area_Pt</td>
                                <td>@item.Condicao_Pt</td>
                                <td>@item.Dano_Pt</td>
                                <td>@item.Gravidade_Pt</td>
                                <td>@item.Quadrante_Pt</td>
                                <td>@item.Severidade_Pt</td>

                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <form asp-controller="Inspecao" asp-action="EditarAvarias" method="post" id="editarAvariaForm">
            <div hidden>
                <input type="text" name="inspAvaria_ID_form_editar" id="avariaIdFormSubmit" value="" />
            </div>
        </form>

        <div class="container">
            <div class="row" id="">
                <p><strong>Avarias em outros CheckPoints</strong></p>
                <table class="table table-striped table-bordered table-hover">
                    <tr class="warning">
                        <th>Área</th>
                        <th>Condicao</th>
                        <th>Dano</th>
                        <th>Gravidade</th>
                        <th>Quadrante</th>
                        <th>Severidade</th>

                    </tr>
                    @foreach (var item in Model.Avarias)
                {
                        @if (!item.InspVeiculo_ID.Equals(Model.InspVeiculo_ID))
                    {
                            <tr>
                                <td>@item.Area_Pt</td>
                                <td>@item.Condicao_Pt</td>
                                <td>@item.Dano_Pt</td>
                                <td>@item.Gravidade_Pt</td>
                                <td>@item.Quadrante_Pt</td>
                                <td>@item.Severidade_Pt</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>

}

src/VDT2/Views/Inspecao/NovaInspecao.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model VDT2.ViewModels.InspecaoDadosGeraisViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/Inspecao/InspecaoDadosGerais.js" asp-append-version="true"></script>


@if (Model == null || Model.ListaCliente == null || Model.ListaLocalCheckPoint == null || Model.ListaLocalInspecao == null || Model.ListaTransportador == null)
{
    <div class="alert alert-danger">
        <p><strong>Erro ao inicializar, por favor tente novamente mais tarde ou entre em contato com o suporte técnico</strong></p>
        <br />
        <button class="btn btn-primary" onclick="history.go(-1)">Voltar</button>
    </div>

}
else
{
    <div class="container">
        @if (TempData["MensagemErro"] != null)
        {
            <div class="alert alert-danger">
                <p>@TempData["MensagemErro"]</p>
            </div>
        }
        <h4><strong>Dados da Inspeção</strong></h4><br />

        <form asp-controller="Inspecao" asp-action="InserirDadosCabecalhoInspecao" method="post" onSubmit="return ValidarFormularioIndex()">

            <div hidden>
                <input type="text" id="edicaoInputini" name="Edicao" value="@Model.Edicao" />
                <input type="text" id="inspecaoIdini" name="Inspecao_ID" value="@Model.Inspecao_ID" />
                <input type="text" id="clienteIdini" value="@Model.Cliente_ID" />
                <input type="text" id="localInspecaoIdini" value="@Model.LocalInspecao_ID" />
                <input type="text" id="localCheckPointIdini" value="@Model.LocalCheckPoint_ID" />
                <input type="text" id="transportadorIdini" value="@Model.Transportador_ID" />
                <input type="text" id="tipotransportadorini" value="@Model.TipoTransportador" />
                <input type="text" id="frotaViagemNomeini" value="@Model.FrotaViagemNome" />
                <input type="text" id="nomeNavioini" value="@Model.NomeNavio" />
                <input type="text" id="idTipoini" value="@Model.IdTipo" />
            </div>

            <div class="row form-group">
                <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <label id="lblUsuario">Usuário: </label>
                    <span id="Usuario" class="">@ViewData["UsuarioNome"]</span>
                </div>
            </div>

            @*Data*@
            <div class="form-group">
                <div class="row">
                    <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                        <label asp-for="@Model.Data">Data da Inspeção</label>
                    </div>
                    <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                        <input id="dataInputID" class="form-control" asp-for="@Model.Data" value="@Model.Data.ToString("yyyy-MM-dd")" type="date" onchange="MensagemAlteracaoData()" contextmenu="@Model.Inspecao.Data" />
                    </div>
                </div>
            </div>



            @*Cliente*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label for="ListaCliente" id="ListaClienteLabelID">Cliente</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <select id="ListaCliente" name="Cliente_ID" class="form-control"
                            asp-items="@(new SelectList(Model.ListaCliente,"Cliente_ID","Nome"))">
                        <option disabled selected>Selecione Cliente</option>
                    </select>
                </div>
            </div>

            @*Local Inspeção*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label for="ListaLocalInspecao">Local Inspeção</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <select id="ListaLocalInspecao" name="LocalInspecao_ID" class="form-control" onchange="PreencheListaCheckPoint()"
                            asp-items="@(new SelectList(Model.ListaLocalInspecao,"LocalInspecao_ID","Nome"))">
                        <option disabled selected>Selecione Local</option>
                    </select>
                </div>
            </div>

            @*Local CheckPoint*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label for="ListaLocalCheckPoint">Local CheckPoint</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <select id="ListaLocalCheckPoint" name="LocalCheckPoint_ID" class="form-control" onchange="PreencheListaTransportador()" onclick="PreencheListaTransportador()" onmouseout="TerrestreOuMaritimo()"
                            asp-items="@(new SelectList(Model.ListaLocalCheckPoint,"LocalCheckPoint_ID", "Nome_Pt"))">
                        <option disabled selected>Selecione CheckPoint</option>
                    </select>
                </div>
            </div>

            @*Transportador*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label for="ListaTransportador" id="labelListaTransportador">Transportador</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <select id="ListaTransportador" name="IdTipo" class="form-control" onchange="TerrestreOuMaritimo()"
                            asp-items="@(new SelectList(Model.ListaTransportador,"IdTipo","Nome"))">
                        <option disabled selected>Selecione Transportador</option>
                    </select>
                </div>
            </div>


            @*Navio*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label id="lblNavio">Navio</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <input class="form-control" id="Navio" name="NomeNavio" value="" type="text" required placeholder="Digite o Navio" />
                </div>
            </div>

            @*Frota*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-2 col-xs-3">
                    <label id="lblFrotaViagem">Frota</label>
                </div>
                <div class="col col-lg-10 col-md-10 col-sm-10 col-xs-9">
                    <input required class="form-control" id="FrotaViagem" name="FrotaViagemNome" value="" type="text" placeholder="Digite a frota" />
                </div>
            </div>


            <br />

            @*Enviar Formulário*@
            <div class="row form-group">
                <div class="col col-lg-2 col-md-2 col-sm-3 col-xs-4">
                    <button type="submit" class="botoesTelaInspecao btn btn-success btn-sm" id="botaoEnviarId" name="botaoEnviar"><span class="glyphicon glyphicon-ok">Gravar</span></button>
                </div>
                <div class="divBotaoLimparTelaNovaInspecao col col-lg-10 col-md-10 col-sm-9 col-xs-8">
                    <button class="botoesTelaInspecao btn btn-warning btn-sm" name="botaoLimpar" onclick="form.reset()"><span class="glyphicon glyphicon-erase"></span> Limpar</button>
                </div>
            </div>

        </form>
    </div>


}